specVersion: 0.0.1
description: The project for getting the on chain data of Kusama
repository: 'https://github.com/parallel-finance/auction-subquery'
schema: ./schema.graphql
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  #endpoint: wss://testnet-relay-rpc.parallel.fi
  dictionary: "https://api.subquery.network/sq/subquery/dictionary-kusama"
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 8858548
    mapping:
      handlers:
        - handler: handleContributionCall
          kind: substrate/CallHandler
          filter:
            success: true
